# Generated by Django 4.0.3 on 2022-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='number2',
            field=models.IntegerField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='sum',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
