# Generated by Django 4.0.3 on 2022-05-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_numbers_number2_alter_numbers_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='number1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='number2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='sum',
            field=models.IntegerField(null=True),
        ),
    ]
