# Generated by Django 4.0.3 on 2022-05-02 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_numbers_number1_alter_numbers_number2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbers',
            name='number1',
        ),
        migrations.RemoveField(
            model_name='numbers',
            name='number2',
        ),
        migrations.RemoveField(
            model_name='numbers',
            name='sum',
        ),
        migrations.AddField(
            model_name='numbers',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.CharField(max_length=200)),
                ('numbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.numbers')),
            ],
        ),
    ]
