# Generated by Django 4.0.3 on 2022-05-02 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_numbers_number1_remove_numbers_number2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='numbers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.numbers'),
        ),
    ]
